### ISSUE TITLE
fatal error: concurrent map writes after alert flushing

### ISSUE THREAD

**Issue by sky-AndreCrujo** [prometheus/alertmanager#1217]
**What did you do?**
AM was running as expected, an alert was resolved and flushed.

**What did you expect to see?**
AM shouldn't have crashed.

**What did you see instead? Under which circumstances?**
AM crashed.

**Environment**

* System information:
      Dockerized Ubuntu 14.04 x64

* Alertmanager version:
       v0.6.1

* Prometheus version:
      Prometheus 1.8

* Logs:
```
fatal error: concurrent map writes

goroutine 295726 [running]:
runtime.throw(0x9f5edb, 0x15)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42083f698 sp=0xc42083f678
runtime.mapassign(0x946e20, 0xc420137ec0, 0xc42083f760, 0xcfc220)
	/usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc42083f738 sp=0xc42083f698
github.com/prometheus/alertmanager/types.(*memMarker).Status(0xc420146860, 0x95544467ab31e873, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/prometheus/alertmanager/types/types.go:178 +0x14a fp=0xc42083f788 sp=0xc42083f738
github.com/prometheus/alertmanager/types.(*memMarker).Inhibited(0xc420146860, 0x95544467ab31e873, 0x0, 0xc42083f898, 0x4d6acb, 0xc4200f40e0)
	/go/src/github.com/prometheus/alertmanager/types/types.go:207 +0x4d fp=0xc42083f818 sp=0xc42083f788
github.com/prometheus/alertmanager/notify.(*InhibitStage).Exec(0xc4202b5380, 0xc79360, 0xc4207b0000, 0xc420638000, 0x1, 0x1, 0x401f15, 0xc4202722f0, 0xc420272600, 0xc42083f928, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:314 +0xa3 fp=0xc42083f8a8 sp=0xc42083f818
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc4202c41e0, 0x3, 0x3, 0xc79360, 0xc4207b0000, 0xc420638000, 0x1, 0x1, 0xc4207b0001, 0x91cfa0, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:259 +0xa5 fp=0xc42083f930 sp=0xc42083f8a8
github.com/prometheus/alertmanager/notify.(*MultiStage).Exec(0xc4202b5500, 0xc79360, 0xc4207b0000, 0xc420638000, 0x1, 0x1, 0xc4208e8100, 0xa0, 0xc4208e80c0, 0x38, ...)
	<autogenerated>:6 +0xad fp=0xc42083f9b8 sp=0xc42083f930
github.com/prometheus/alertmanager/notify.RoutingStage.Exec(0xc4202c40c0, 0xc79360, 0xc4207b0000, 0xc420638000, 0x1, 0x1, 0x0, 0x0, 0xc420272305, 0xc4208e80c0, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:245 +0xde fp=0xc42083fa30 sp=0xc42083f9b8
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1(0xc79360, 0xc4207b0000, 0xc420638000, 0x1, 0x1, 0x2)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:264 +0x86 fp=0xc42083fae8 sp=0xc42083fa30
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run.func1(0xc420638000, 0x1, 0x1, 0x2)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:372 +0x58 fp=0xc42083fb28 sp=0xc42083fae8
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).flush(0xc42077c240, 0xc42083ff20)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:432 +0x47f fp=0xc42083fd80 sp=0xc42083fb28
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run(0xc42077c240, 0xc420742340)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:373 +0x88c fp=0xc42083ffd0 sp=0xc42083fd80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42083ffd8 sp=0xc42083ffd0
created by github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:269 +0x32c

goroutine 1 [chan receive, 5464 minutes]:
main.main()
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:292 +0x1b62

goroutine 5 [syscall, 5464 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 17 [select]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*localPeer).actorLoop(0xc420137440, 0xc420059440)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/local_peer.go:141 +0x120
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newLocalPeer
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/local_peer.go:31 +0x12c

goroutine 18 [select]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*routes).run(0xc42005b480, 0xc420059560, 0xc4200595c0, 0xc420059620)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/routes.go:177 +0x1a3
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newRoutes
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/routes.go:44 +0x453

goroutine 19 [select, 4 minutes]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*connectionMaker).queryLoop(0xc4200596e0, 0xc420059680)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/connection_maker.go:221 +0x15c
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newConnectionMaker
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/connection_maker.go:74 +0x21a

goroutine 25 [select, 6 minutes]:
github.com/prometheus/alertmanager/nflog.(*nlog).run(0xc42005b680)
	/go/src/github.com/prometheus/alertmanager/nflog/nflog.go:308 +0x2f8
created by github.com/prometheus/alertmanager/nflog.New
	/go/src/github.com/prometheus/alertmanager/nflog/nflog.go:267 +0x35a

goroutine 31 [select, 6 minutes]:
github.com/prometheus/alertmanager/silence.(*Silences).Maintenance(0xc4201e42d0, 0xd18c2e2800, 0xc420216020, 0xd, 0xc420059740)
	/go/src/github.com/prometheus/alertmanager/silence/silence.go:253 +0x2e5
main.main.func3(0xc4201e42d0, 0xc42011d5f0, 0xc420059740, 0xc42011d950)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:158 +0xb1
created by main.main
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:160 +0xfda

goroutine 32 [IO wait, 5464 minutes]:
net.runtime_pollWait(0x7f031dc75148, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201be768, 0x72, 0x0, 0xc420234000)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201be768, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4201be700, 0x0, 0xc72920, 0xc420234000)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000c260, 0xc420230030, 0xc420191788, 0x18)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000c260, 0xa0e340, 0xc42000c260, 0x0)
	/usr/local/go/src/net/tcpsock.go:215 +0x49
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*Router).listenTCP.func1(0xc42000c260, 0xc4200d02a0)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/router.go:109 +0x59
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*Router).listenTCP
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/router.go:117 +0x16a

goroutine 49 [select, 6 minutes]:
github.com/prometheus/alertmanager/provider/mem.(*Alerts).runGC(0xc4201e4370)
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:54 +0x259
created by github.com/prometheus/alertmanager/provider/mem.NewAlerts
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:47 +0x15f

goroutine 81 [chan receive, 5464 minutes]:
github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe.func1(0xc4201e4370, 0x0, 0xc420218120, 0xcfb5f8, 0x0, 0x0, 0xc420218180)
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:114 +0x19b
created by github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:115 +0x1aa

goroutine 65 [select, 6 minutes]:
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).runGC(0xc420275320)
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:55 +0x160
created by github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Run
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:72 +0xbf

goroutine 52 [select]:
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).run(0xc4200d8d80, 0xc77560, 0xc42021a040)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:178 +0x6d5
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).Run(0xc4200d8d80)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:68 +0x158
created by main.main.func7
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:251 +0x5db

goroutine 53 [select, 4 minutes]:
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Run(0xc420275320)
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:78 +0x352
created by main.main.func7
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:252 +0x603

goroutine 66 [chan receive, 5464 minutes]:
github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe.func1(0xc4201e4370, 0x1, 0xc4201ee0c0, 0xcfb5f8, 0x0, 0x0, 0xc4201ee120)
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:114 +0x19b
created by github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:115 +0x1aa

goroutine 165 [IO wait]:
net.runtime_pollWait(0x7f031dc75088, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4203ef028, 0x72, 0x0, 0xc42000a3e0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4203ef028, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4203eefc0, 0x0, 0xc72920, 0xc42000a3e0)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc420154180, 0xc4207b3020, 0x93c8a0, 0xffffffffffffffff)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc420154180, 0xc4201ffe58, 0xc4201ffe60, 0xc4201ffe50)
	/usr/local/go/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc420154180, 0xa0e4d0, 0xc4207b2fa0, 0xc78e20, 0xc4200efc20)
	/usr/local/go/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc420088420, 0xc78760, 0xc420154180, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc420088420, 0xc420088420, 0x70e241)
	/usr/local/go/src/net/http/server.go:2585 +0xb0
net/http.ListenAndServe(0x9e9cc8, 0x5, 0xc71a60, 0xc4202b5540, 0xc420027fb8, 0x722cf9)
	/usr/local/go/src/net/http/server.go:2787 +0x7f
main.listen(0x9e9cc8, 0x5, 0xc4202b5540)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:389 +0x4f
created by main.main
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:268 +0x1957

goroutine 166 [select, 5464 minutes, locked to thread]:
runtime.gopark(0xa0eac8, 0x0, 0x9eb6e2, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc42018af50, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc42018af50)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 167 [select, 5464 minutes]:
main.main.func8(0xc420242960, 0xc420242900, 0xc4202753e0, 0xc4200d8ab0)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:281 +0x108
created by main.main
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:287 +0x1b2b

goroutine 146810 [IO wait, 18 minutes]:
net.runtime_pollWait(0x7f031dc74e48, 0x72, 0x6)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42013a068, 0x72, 0xc73e60, 0xc6f410)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42013a068, 0xc4206dc000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42013a000, 0xc4206dc000, 0x1000, 0x1000, 0x0, 0xc73e60, 0xc6f410)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420aea138, 0xc4206dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc420256f00, 0xc4206dc000, 0x1000, 0x1000, 0x10000c420421860, 0xc4209a1920, 0x4046cb)
	/usr/local/go/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42014c4e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc42014c4e0, 0x71d60a, 0xc4207c3520, 0x42ca84, 0xc4209a19a8, 0x4558c0, 0xc42063cea0)
	/usr/local/go/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc42014c4e0, 0xc4200bbc00, 0x100, 0xf8, 0x9dc1c0, 0xc420aea138, 0x4606a2)
	/usr/local/go/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc4204205d0, 0xc4209a1ac8, 0xc4209a1ac8, 0x40fdb8, 0x100, 0x9dc1c0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc4204205d0, 0xc4200bbc00, 0x72, 0x8000000000000000, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc42014c4e0, 0x0, 0xc4200bbc00, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc4206e9e00, 0xc78d60, 0xc420256ec0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc4206e9e00, 0xc78d60, 0xc420256ec0)
	/usr/local/go/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 295725 [runnable]:
sync.(*RWMutex).RUnlock(0xc420146868)
	/usr/local/go/src/sync/rwmutex.go:55 +0x8c
github.com/prometheus/alertmanager/types.(*memMarker).Status(0xc420146860, 0x95544467ab31e873, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/prometheus/alertmanager/types/types.go:181 +0xf0
github.com/prometheus/alertmanager/types.(*memMarker).Inhibited(0xc420146860, 0x95544467ab31e873, 0x0, 0xc4209a3898, 0x4d6acb, 0xc4203ef650)
	/go/src/github.com/prometheus/alertmanager/types/types.go:207 +0x4d
github.com/prometheus/alertmanager/notify.(*InhibitStage).Exec(0xc4202b5380, 0xc79360, 0xc4201c3800, 0xc420154068, 0x1, 0x1, 0x401f15, 0xc42011c730, 0xc42011c8b0, 0xc4209a3928, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:314 +0xa3
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc4202c4150, 0x3, 0x3, 0xc79360, 0xc4201c3800, 0xc420154068, 0x1, 0x1, 0xc4201c3801, 0x91cfa0, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:259 +0xa5
github.com/prometheus/alertmanager/notify.(*MultiStage).Exec(0xc4202b5440, 0xc79360, 0xc4201c3800, 0xc420154068, 0x1, 0x1, 0xc4202b9dc0, 0x50, 0xc4202b9540, 0x38, ...)
	<autogenerated>:6 +0xad
github.com/prometheus/alertmanager/notify.RoutingStage.Exec(0xc4202c40c0, 0xc79360, 0xc4201c3800, 0xc420154068, 0x1, 0x1, 0x0, 0x0, 0xc42011c705, 0xc4202b9540, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:245 +0xde
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1(0xc79360, 0xc4201c3800, 0xc420154068, 0x1, 0x1, 0x2)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:264 +0x86
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run.func1(0xc420154068, 0x1, 0x1, 0x2)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:372 +0x58
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).flush(0xc42077c120, 0xc4209a3f20)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:432 +0x47f
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run(0xc42077c120, 0xc4207422d0)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:373 +0x88c
created by github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:269 +0x32c

goroutine 147755 [IO wait, 8 minutes]:
net.runtime_pollWait(0x7f031dc74fc8, 0x72, 0x8)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4203ef098, 0x72, 0xc73e60, 0xc6f410)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4203ef098, 0xc42086a000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4203ef030, 0xc42086a000, 0x1000, 0x1000, 0x0, 0xc73e60, 0xc6f410)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420aea080, 0xc42086a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc4205b6900, 0xc42086a000, 0x1000, 0x1000, 0x10000c4201c3d10, 0xc420841920, 0x4046cb)
	/usr/local/go/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42014c0c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc42014c0c0, 0x71d60a, 0xc42074f6c0, 0x42ca84, 0xc4208419a8, 0x4558c0, 0xc42068aea0)
	/usr/local/go/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc42014c0c0, 0xc4200bbd00, 0x100, 0xf8, 0x9dc1c0, 0xc420aea080, 0x4606a2)
	/usr/local/go/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc4201c2870, 0xc420841ac8, 0xc420841ac8, 0x40fdb8, 0x100, 0x9dc1c0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc4201c2870, 0xc4200bbd00, 0x72, 0x8000000000000000, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc42014c0c0, 0x0, 0xc4200bbd00, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc420a323c0, 0xc78d60, 0xc4205b6880, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc420a323c0, 0xc78d60, 0xc4205b6880)
	/usr/local/go/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 146518 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f031dc74f08, 0x72, 0x7)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201326f8, 0x72, 0xc73e60, 0xc6f410)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201326f8, 0xc42097a000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420132690, 0xc42097a000, 0x1000, 0x1000, 0x0, 0xc73e60, 0xc6f410)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420aea010, 0xc42097a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc420126a80, 0xc42097a000, 0x1000, 0x1000, 0x10000c4202369f0, 0xc42083d920, 0x4046cb)
	/usr/local/go/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc420274120)
	/usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc420274120, 0x71d60a, 0xc4206a2d00, 0x42ca84, 0xc42083d9a8, 0x4558c0, 0xc4208116c0)
	/usr/local/go/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc420274120, 0xc420778800, 0x100, 0xf8, 0x9dc1c0, 0xc420aea010, 0x4606a2)
	/usr/local/go/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc420420ed0, 0xc42083dac8, 0xc42083dac8, 0x40fdb8, 0x100, 0x9dc1c0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc420420ed0, 0xc420778800, 0x72, 0x8000000000000000, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc420274120, 0x0, 0xc420778800, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc4200bea00, 0xc78d60, 0xc420126a40, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc4200bea00, 0xc78d60, 0xc420126a40)
	/usr/local/go/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by simonpasquier** [comment]
You're running an old (v0.6.1) version of AlertManager. Can you update to the latest AlertManager version?

**Comment by sky-AndreCrujo** [comment]
Sure. Just wanted to report the issue in case it was still outstanding.

**Comment by simonpasquier** [comment]
Closing for now. Feel free to reopen if you can reproduce it with the latest version.
