### ISSUE TITLE
Panic on access :9093/api/v2/status after upgrade to 0.16.0

### ISSUE THREAD

**Issue by vbatychko-modeln** [prometheus/alertmanager#1725]
**What did you do?**
curl :9093/api/v2/status

**What did you expect to see?**
Valid REST reply

**What did you see instead? Under which circumstances?**
curl: (52) Empty reply from server

```
2019/01/25 14:53:31 http: panic serving 127.0.0.1:34314: runtime error: invalid memory address or nil pointer dereference
alertmanager: goroutine 325160 [running]:
alertmanager: net/http.(*conn).serve.func1(0xc00066ea00)
alertmanager: /usr/local/go/src/net/http/server.go:1746 +0xd0
alertmanager: panic(0xc36040, 0x149c340)
alertmanager: /usr/local/go/src/runtime/panic.go:513 +0x1b9
alertmanager: github.com/prometheus/alertmanager/cluster.(*Peer).Name(0x0, 0xc000784a20, 0xc00002f7e0)
alertmanager: /app/cluster/cluster.go:554 +0x22
alertmanager: github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler(0xc00002f7a0, 0xc00065c000, 0x0, 0x0)
alertmanager: /app/api/v2/api.go:132 +0xb7
alertmanager: github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler-fm(0xc00065c000, 0xb1cb01, 0xc000960728)
alertmanager: /app/api/v2/api.go:102 +0x34
alertmanager: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.GetStatusHandlerFunc.Handle(0xc0004d0db0, 0xc00065c000, 0xc000163800, 0xecbf40)
alertmanager: /app/api/v2/restapi/operations/general/get_status.go:19 +0x30
alertmanager: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.(*GetStatus).ServeHTTP(0xc0004eed80, 0xed4260, 0xc000c7b7a0, 0xc00065c000)
alertmanager: /app/api/v2/restapi/operations/general/get_status.go:54 +0x164
alertmanager: github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0xed4260, 0xc000c7b7a0, 0xc00065c000)
alertmanager: /app/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x75
alertmanager: net/http.HandlerFunc.ServeHTTP(0xc0004d14e0, 0xed4260, 0xc000c7b7a0, 0xc00065c000)
alertmanager: /usr/local/go/src/net/http/server.go:1964 +0x44
alertmanager: github.com/go-openapi/runtime/middleware.NewRouter.func1(0xed4260, 0xc000c7b7a0, 0xc000162a00)
alertmanager: /app/vendor/github.com/go-openapi/runtime/middleware/router.go:76 +0x358
alertmanager: net/http.HandlerFunc.ServeHTTP(0xc0006bd860, 0xed4260, 0xc000c7b7a0, 0xc000162a00)
alertmanager: /usr/local/go/src/net/http/server.go:1964 +0x44
alertmanager: github.com/go-openapi/runtime/middleware.Spec.func1(0xed4260, 0xc000c7b7a0, 0xc000162a00)
alertmanager: /app/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x73
alertmanager: net/http.HandlerFunc.ServeHTTP(0xc0004e7500, 0xed4260, 0xc000c7b7a0, 0xc000162a00)
alertmanager: /usr/local/go/src/net/http/server.go:1964 +0x44
alertmanager: github.com/rs/cors.(*Cors).Handler.func1(0xed4260, 0xc000c7b7a0, 0xc000162a00)
alertmanager: /app/vendor/github.com/rs/cors/cors.go:207 +0xf2
alertmanager: net/http.HandlerFunc.ServeHTTP(0xc0006bd880, 0xed4260, 0xc000c7b7a0, 0xc000162a00)
alertmanager: /usr/local/go/src/net/http/server.go:1964 +0x44
alertmanager: net/http.StripPrefix.func1(0xed4260, 0xc000c7b7a0, 0xc000162900)
alertmanager: /usr/local/go/src/net/http/server.go:2003 +0x18b
alertmanager: net/http.HandlerFunc.ServeHTTP(0xc0004c2a20, 0xed4260, 0xc000c7b7a0, 0xc000162900)
alertmanager: /usr/local/go/src/net/http/server.go:1964 +0x44
alertmanager: net/http.(*ServeMux).ServeHTTP(0xc0004c29c0, 0xed4260, 0xc000c7b7a0, 0xc000162900)
alertmanager: /usr/local/go/src/net/http/server.go:2361 +0x127
alertmanager: net/http.serverHandler.ServeHTTP(0xc00061ef70, 0xed4260, 0xc000c7b7a0, 0xc000162900)
alertmanager: /usr/local/go/src/net/http/server.go:2741 +0xab
alertmanager: net/http.(*conn).serve(0xc00066ea00, 0xed50e0, 0xc0011a8580)
alertmanager: /usr/local/go/src/net/http/server.go:1847 +0x646
alertmanager: created by net/http.(*Server).Serve
alertmanager: /usr/local/go/src/net/http/server.go:2851 +0x2f5
```
**Environment**

* System information:

Linux 4.14.70-72.55.amzn2.x86_64 x86_64

* Alertmanager version:

alertmanager, version 0.16.0 (branch: HEAD, revision: 73bdd966e0055f3b828340ade3ef1f3a38169cdc)
  build user:       root@fbea1f55d584
  build date:       20190121-12:58:06
  go version:       go1.11.4

* Prometheus version:

prometheus, version 2.6.0 (branch: HEAD, revision: dbd1d58c894775c0788470944b818cc724f550fb)
  build user:       root@bf5760470f13
  build date:       20181217-15:14:46
  go version:       go1.11.3

* Alertmanager configuration file (shrinked):
```
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname','group']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 24h
  receiver: null
routes:
...

receivers:
- name: 'null'
...

templates:
 - /opt/alertmanager/templates/*.tmpl

inhibit_rules:
...
```

* Alertmanager commandline flags:
```
--config.file /opt/alertmanager/alertmanager.yml --storage.path /opt/alertmanager/data --web.external-url http://alertmanager.domain.com --web.listen-address=127.0.0.1:9093 --cluster.listen-address=
```

**Comment by stuartnelson3** [comment]
Can you include your command line flags and a sanitized config file?

**Comment by vbatychko-modeln** [comment]
@stuartnelson3 updated ticket summary

**Comment by mxinden** [comment]
Hi @vbatychko-modeln,

Thanks for the detailed report. Can you try https://github.com/prometheus/alertmanager/pull/1726?

**Comment by vbatychko-modeln** [comment]
@mxinden Same problem, with slightly different stacktrace:

```
2019/01/25 18:05:05 http: panic serving 127.0.0.1:60132: runtime error: invalid memory address or nil pointer dereference
goroutine 416 [running]:
net/http.(*conn).serve.func1(0xc000c206e0)
/.1/prometheus/go/src/net/http/server.go:1746 +0xd0
panic(0xc36040, 0x14a3340)
/.1/prometheus/go/src/runtime/panic.go:513 +0x1b9
github.com/prometheus/alertmanager/cluster.(*Peer).Name(0x0, 0xc000df5a50, 0xc00002fbd0)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/cluster/cluster.go:554 +0x22
github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler(0xc00002fb90, 0xc0002d5600, 0x0, 0x0)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/api/v2/api.go:132 +0xb7
github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler-fm(0xc0002d5600, 0xb1cb01, 0xc000400038)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/api/v2/api.go:102 +0x34
github.com/prometheus/alertmanager/api/v2/restapi/operations/general.GetStatusHandlerFunc.Handle(0xc0003aa400, 0xc0002d5600, 0xc0002d5500, 0xecbf40)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/api/v2/restapi/operations/general/get_status.go:19 +0x30
github.com/prometheus/alertmanager/api/v2/restapi/operations/general.(*GetStatus).ServeHTTP(0xc0003bd880, 0xed42a0, 0xc000bb6d20, 0xc0002d5600)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/api/v2/restapi/operations/general/get_status.go:54 +0x164
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0xed42a0, 0xc000bb6d20, 0xc0002d5600)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0003aab40, 0xed42a0, 0xc000bb6d20, 0xc0002d5600)
/.1/prometheus/go/src/net/http/server.go:1964 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0xed42a0, 0xc000bb6d20, 0xc0002d5400)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/vendor/github.com/go-openapi/runtime/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc0002f19a0, 0xed42a0, 0xc000bb6d20, 0xc0002d5400)
/.1/prometheus/go/src/net/http/server.go:1964 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0xed42a0, 0xc000bb6d20, 0xc0002d5400)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x73
net/http.HandlerFunc.ServeHTTP(0xc0008adf00, 0xed42a0, 0xc000bb6d20, 0xc0002d5400)
/.1/prometheus/go/src/net/http/server.go:1964 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0xed42a0, 0xc000bb6d20, 0xc0002d5400)
/opt/prometheus/go/src/github.com/prometheus/alertmanager/vendor/github.com/rs/cors/cors.go:207 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc0002f1a20, 0xed42a0, 0xc000bb6d20, 0xc0002d5400)
/.1/prometheus/go/src/net/http/server.go:1964 +0x44
net/http.StripPrefix.func1(0xed42a0, 0xc000bb6d20, 0xc0002d5300)
/.1/prometheus/go/src/net/http/server.go:2003 +0x18b
net/http.HandlerFunc.ServeHTTP(0xc000631dd0, 0xed42a0, 0xc000bb6d20, 0xc0002d5300)
/.1/prometheus/go/src/net/http/server.go:1964 +0x44
```

**Comment by mxinden** [comment]
I missed another nil pointer dereference. I updated https://github.com/prometheus/alertmanager/pull/1726, can you give this another shot?

**Comment by vbatychko-modeln** [comment]
@mxinden That fixed problem with REST query, but UI reports following error:

```
Unexpected response from api: Problem with the value at json.cluster: null Expecting an OBJECT with a field named `peers`
```

**Comment by mxinden** [comment]
@vbatychko-modeln https://github.com/prometheus/alertmanager/pull/1726 will include a bug fix also touching the UI, which would be released as v0.16.1. https://github.com/prometheus/alertmanager/pull/1728 will clean things up introducing a breaking change which would be released in v0.17.0.

Would you mind giving https://github.com/prometheus/alertmanager/pull/1726 another try?

**Comment by vbatychko-modeln** [comment]
@mxinden I can confirm, bug is fixed with #1726 . Thanks!

**Comment by simonpasquier** [comment]
Closed by #1726

**Comment by mshivanna** [comment]
We are on v0.21.0 but i still have the below issue on UI 
```
Unexpected response from api: Problem with the value at json.cluster: { "peers": [], "status": "disabled" } Expecting an OBJECT with a field named `name`

**Comment by roidelapluie** [comment]
Thanks @mshivanna , can you open a new issue?

**Comment by mshivanna** [comment]
Sure will do
