### ISSUE TITLE
failed to join cluster and  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fcddk** [prometheus/alertmanager#2190]
version v0.18.0
log:
level=info ts=2020-02-20T09:59:12.859Z caller=main.go:219 msg="Starting Alertmanager" version="(version=0.19.0, branch=cms-2.0, revision=de7171aceb59a238f7861d635b3e56ef163b8562)"
level=info ts=2020-02-20T09:59:12.860Z caller=main.go:220 build_context="(go=go1.12.5, user=root@master1, date=20200217-04:27:43)"
level=debug ts=2020-02-20T09:59:12.920Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=alertmanager-0.alertmanager-svc:9094,alertmanager-1.alertmanager-svc:9094,alertmanager-2.alertmanager-svc:9094
level=info ts=2020-02-20T09:59:12.922Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=10.151.49.55 port=9094
level=debug ts=2020-02-20T09:59:12.926Z caller=delegate.go:230 component=cluster received=NotifyJoin node=01E1H0JY8TC6R9QR8N82R12T43 addr=10.151.49.55:9094
level=debug ts=2020-02-20T09:59:12.948Z caller=cluster.go:306 component=cluster memberlist="2020/02/20 09:59:12 [WARN] memberlist: Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 10.150.0.3:53: server misbehaving\n"
level=debug ts=2020-02-20T09:59:12.963Z caller=cluster.go:306 component=cluster memberlist="2020/02/20 09:59:12 [WARN] memberlist: Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 10.150.0.3:53: server misbehaving\n"
level=debug ts=2020-02-20T09:59:12.981Z caller=cluster.go:306 component=cluster memberlist="2020/02/20 09:59:12 [WARN] memberlist: Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 10.150.0.3:53: server misbehaving\n"
level=warn ts=2020-02-20T09:59:12.981Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="3 errors occurred:\n\t* Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 10.150.0.3:53: server misbehaving\n\t* Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 10.150.0.3:53: server misbehaving\n\t* Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 10.150.0.3:53: server misbehaving\n\n"
level=info ts=2020-02-20T09:59:12.981Z caller=cluster.go:230 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2020-02-20T09:59:12.981Z caller=main.go:310 msg="unable to join gossip mesh" err="3 errors occurred:\n\t* Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 10.150.0.3:53: server misbehaving\n\t* Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 10.150.0.3:53: server misbehaving\n\t* Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 10.150.0.3:53: server misbehaving\n\n"
level=info ts=2020-02-20T09:59:12.982Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=debug ts=2020-02-20T09:59:13.252Z caller=main.go:358 externalURL=http://alertmanager-0:9093
level=info ts=2020-02-20T09:59:13.253Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config.yml
level=info ts=2020-02-20T09:59:13.255Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config.yml
level=debug ts=2020-02-20T09:59:13.284Z caller=cluster.go:539 component=cluster msg="leaving cluster"
level=debug ts=2020-02-20T09:59:13.285Z caller=delegate.go:236 component=cluster received=NotifyLeave node=01E1H0JY8TC6R9QR8N82R12T43 addr=10.151.49.55:9094
level=debug ts=2020-02-20T09:59:13.285Z caller=cluster.go:492 component=cluster msg="peer left" peer=01E1H0JY8TC6R9QR8N82R12T43
level=debug ts=2020-02-20T09:59:13.285Z caller=nflog.go:336 component=nflog msg="Running maintenance"
level=info ts=2020-02-20T09:59:13.286Z caller=cluster.go:632 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=303.66376ms
level=debug ts=2020-02-20T09:59:13.287Z caller=silence.go:350 component=silences msg="Running maintenance"
level=debug ts=2020-02-20T09:59:13.319Z caller=nflog.go:338 component=nflog msg="Maintenance done" duration=33.662342ms size=0
level=debug ts=2020-02-20T09:59:13.333Z caller=silence.go:352 component=silences msg="Maintenance done" duration=46.529916ms size=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa8aa44]

goroutine 1 [running]:
main.run.func7(0xc00051b2d0, 0x8, 0x40)
	/opt/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:426 +0x534
github.com/prometheus/alertmanager/config.(*Coordinator).notifySubscribers(0xc0007bca80, 0xc0007ef5c0, 0x4)
	/opt/go/src/github.com/prometheus/alertmanager/config/coordinator.go:88 +0x84
github.com/prometheus/alertmanager/config.(*Coordinator).Reload(0xc0007bca80, 0x0, 0x0)
	/opt/go/src/github.com/prometheus/alertmanager/config/coordinator.go:136 +0x6f0
main.run(0x0)
	/opt/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:458 +0x4608
main.main()
	/opt/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:175 +0x34

**Comment by roidelapluie** [comment]
Thanks for your report. We will look into it. While it is not nice to panic, it also looks like your DNS server is not working properly.

**Comment by simonpasquier** [comment]
Can you share the configuration you're trying to reload?

**Comment by simonpasquier** [comment]
Also can you share the full logs?

**Comment by fcddk** [comment]
level=info ts=2020-03-03T10:45:21.396Z caller=main.go:197 msg="Starting Alertmanager" version="(version=0.18.0, branch=feature, revision=85ef47a8aa150dc138aa85558afe757226f6e221)"
level=info ts=2020-03-03T10:45:21.396Z caller=main.go:198 build_context="(go=go1.13.8, user=root@master1, date=20200220-08:33:07)"
level=debug ts=2020-03-03T10:46:09.424Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=alertmanager-0.alertmanager-svc:9094,alertmanager-1.alertmanager-svc:9094,alertmanager-2.alertmanager-svc:9094
level=info ts=2020-03-03T10:46:09.428Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=172.17.0.3 port=9094
level=debug ts=2020-03-03T10:46:09.432Z caller=delegate.go:230 component=cluster received=NotifyJoin node=01E2G01GRMZ5RFTFPRSZ243PYE addr=172.17.0.3:9094
level=debug ts=2020-03-03T10:46:11.435Z caller=cluster.go:306 component=cluster memberlist="2020/03/03 10:46:11 [DEBUG] memberlist: TCP-first lookup failed for 'alertmanager-0.alertmanager-svc:9094', falling back to UDP: dial tcp 114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-03T10:46:27.443Z caller=cluster.go:306 component=cluster memberlist="2020/03/03 10:46:27 [WARN] memberlist: Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:33380->114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-03T10:46:29.444Z caller=cluster.go:306 component=cluster memberlist="2020/03/03 10:46:29 [DEBUG] memberlist: TCP-first lookup failed for 'alertmanager-1.alertmanager-svc:9094', falling back to UDP: dial tcp 114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-03T10:46:45.449Z caller=cluster.go:306 component=cluster memberlist="2020/03/03 10:46:45 [WARN] memberlist: Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:55118->114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-03T10:46:47.451Z caller=cluster.go:306 component=cluster memberlist="2020/03/03 10:46:47 [DEBUG] memberlist: TCP-first lookup failed for 'alertmanager-2.alertmanager-svc:9094', falling back to UDP: dial tcp 114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-03T10:47:03.457Z caller=cluster.go:306 component=cluster memberlist="2020/03/03 10:47:03 [WARN] memberlist: Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:33004->114.114.114.114:53: i/o timeout\n"
level=warn ts=2020-03-03T10:47:03.457Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="3 errors occurred:\n\t* Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:33380->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:55118->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:33004->114.114.114.114:53: i/o timeout\n\n"
level=info ts=2020-03-03T10:47:03.458Z caller=cluster.go:230 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2020-03-03T10:47:03.458Z caller=main.go:287 msg="unable to join gossip mesh" err="3 errors occurred:\n\t* Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:33380->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:55118->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:33004->114.114.114.114:53: i/o timeout\n\n"
level=info ts=2020-03-03T10:47:03.458Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2020-03-03T10:47:03.630Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config.yml
level=error ts=2020-03-03T10:47:03.630Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="open /etc/alertmanager/config.yml: no such file or directory"
level=debug ts=2020-03-03T10:47:03.630Z caller=cluster.go:539 component=cluster msg="leaving cluster"
level=debug ts=2020-03-03T10:47:03.631Z caller=delegate.go:236 component=cluster received=NotifyLeave node=01E2G01GRMZ5RFTFPRSZ243PYE addr=172.17.0.3:9094
level=debug ts=2020-03-03T10:47:03.631Z caller=cluster.go:492 component=cluster msg="peer left" peer=01E2G01GRMZ5RFTFPRSZ243PYE
level=info ts=2020-03-03T10:47:03.631Z caller=cluster.go:632 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=172.39528ms
level=debug ts=2020-03-03T10:47:03.631Z caller=nflog.go:336 component=nflog msg="Running maintenance"
level=debug ts=2020-03-03T10:47:03.631Z caller=silence.go:350 component=silences msg="Running maintenance"
level=debug ts=2020-03-03T10:47:03.652Z caller=nflog.go:338 component=nflog msg="Maintenance done" duration=21.3083ms size=0
level=debug ts=2020-03-03T10:47:03.660Z caller=silence.go:352 component=silences msg="Maintenance done" duration=29.45028ms size=0

**Comment by fcddk** [comment]
level=info ts=2020-03-09T01:01:05.583Z caller=main.go:197 msg="Starting Alertmanager" version="(version=0.18.0, branch=feature, revision=85ef47a8aa150dc138aa85558afe757226f6e221)"
level=info ts=2020-03-09T01:01:05.583Z caller=main.go:198 build_context="(go=go1.13.8, user=root@master1, date=20200220-08:33:07)"
level=debug ts=2020-03-09T01:01:53.635Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=alertmanager-0.alertmanager-svc:9094,alertmanager-1.alertmanager-svc:9094,alertmanager-2.alertmanager-svc:9094
level=info ts=2020-03-09T01:01:53.638Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=172.17.0.3 port=9094
level=debug ts=2020-03-09T01:01:53.641Z caller=delegate.go:230 component=cluster received=NotifyJoin node=01E2YD00K6VQ1GBK91KSWFCRKQ addr=172.17.0.3:9094
level=debug ts=2020-03-09T01:01:55.644Z caller=cluster.go:306 component=cluster memberlist="2020/03/09 01:01:55 [DEBUG] memberlist: TCP-first lookup failed for 'alertmanager-0.alertmanager-svc:9094', falling back to UDP: dial tcp 114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-09T01:02:11.652Z caller=cluster.go:306 component=cluster memberlist="2020/03/09 01:02:11 [WARN] memberlist: Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:44583->114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-09T01:02:13.661Z caller=cluster.go:306 component=cluster memberlist="2020/03/09 01:02:13 [DEBUG] memberlist: TCP-first lookup failed for 'alertmanager-1.alertmanager-svc:9094', falling back to UDP: dial tcp 114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-09T01:02:29.669Z caller=cluster.go:306 component=cluster memberlist="2020/03/09 01:02:29 [WARN] memberlist: Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:39521->114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-09T01:02:31.670Z caller=cluster.go:306 component=cluster memberlist="2020/03/09 01:02:31 [DEBUG] memberlist: TCP-first lookup failed for 'alertmanager-2.alertmanager-svc:9094', falling back to UDP: dial tcp 114.114.114.114:53: i/o timeout\n"
level=debug ts=2020-03-09T01:02:47.688Z caller=cluster.go:306 component=cluster memberlist="2020/03/09 01:02:47 [WARN] memberlist: Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:51380->114.114.114.114:53: i/o timeout\n"
level=warn ts=2020-03-09T01:02:47.689Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="3 errors occurred:\n\t* Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:44583->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:39521->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:51380->114.114.114.114:53: i/o timeout\n\n"
level=info ts=2020-03-09T01:02:47.689Z caller=cluster.go:230 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2020-03-09T01:02:47.689Z caller=main.go:287 msg="unable to join gossip mesh" err="3 errors occurred:\n\t* Failed to resolve alertmanager-0.alertmanager-svc:9094: lookup alertmanager-0.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:44583->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-1.alertmanager-svc:9094: lookup alertmanager-1.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:39521->114.114.114.114:53: i/o timeout\n\t* Failed to resolve alertmanager-2.alertmanager-svc:9094: lookup alertmanager-2.alertmanager-svc on 114.114.114.114:53: read udp 172.17.0.3:51380->114.114.114.114:53: i/o timeout\n\n"
level=info ts=2020-03-09T01:02:47.692Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2020-03-09T01:02:48.070Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config.yml
level=error ts=2020-03-09T01:02:48.087Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="open /etc/alertmanager/config.yml: no such file or directory"
level=debug ts=2020-03-09T01:02:48.088Z caller=cluster.go:539 component=cluster msg="leaving cluster"
level=debug ts=2020-03-09T01:02:48.088Z caller=delegate.go:236 component=cluster received=NotifyLeave node=01E2YD00K6VQ1GBK91KSWFCRKQ addr=172.17.0.3:9094
level=debug ts=2020-03-09T01:02:48.088Z caller=cluster.go:492 component=cluster msg="peer left" peer=01E2YD00K6VQ1GBK91KSWFCRKQ
level=debug ts=2020-03-09T01:02:48.088Z caller=nflog.go:336 component=nflog msg="Running maintenance"
level=info ts=2020-03-09T01:02:48.090Z caller=cluster.go:632 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=398.29656ms
level=debug ts=2020-03-09T01:02:48.091Z caller=silence.go:350 component=silences msg="Running maintenance"
level=debug ts=2020-03-09T01:02:48.110Z caller=nflog.go:338 component=nflog msg="Maintenance done" duration=21.9116ms size=0
level=debug ts=2020-03-09T01:02:48.118Z caller=silence.go:352 component=silences msg="Maintenance done" duration=27.66526ms size=0
[INFO  tini (1)] Spawned child process '/bin/alertmanager' with pid '5'
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[TRACE tini (1)] No child to reap
[DEBUG tini (1)] Received SIGCHLD
[DEBUG tini (1)] Reaped child with pid: '5'
[INFO  tini (1)] Main child exited normally (with status '1')
[TRACE tini (1)] No child to wait
[TRACE tini (1)] Exiting: child has exited

**Comment by fcddk** [comment]
Received SIGCHLD

**Comment by simonpasquier** [comment]
The logs say that it can't load the configuration so this isn't the same error as posted originally...

```
level=error ts=2020-03-09T01:02:48.087Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="open /etc/alertmanager/config.yml: no such file or directory"
```

**Comment by TheMeier** [comment]
This issue is very old. If you still see something like that please re-open it or file a new one.
