### ISSUE TITLE
Master branch (date=20210413): flag --cluster.listen-address= or --cluster.listen-address="" produces segmentation violation.

### ISSUE THREAD

**Issue by jobenvil** [prometheus/alertmanager#2549]
**What did you do?**

Since today, I discovered the tag _master_, 🥰  on docker and I changed the tags for `blackbox_exporter` ✔️  and `alertmanager` ❎ . It makes sense since the latest tagged versions are "pretty" old. Changing the tag to `master` is a good recipe, well, maybe sometimes not so good ...

While changing the docker tag from _latest_ (`date=20200617-08:54:02`) to _master_ (`date=20210413-15:17:06`) on `alertmanager`, appeared the failure. 

**What did you expect to see?**

A beautiful 💚 world 

**What did you see instead? Under which circumstances?**

Segmentation violation on `alartmanager` logs, `502` on GUI (status) 💔 

Appx every 15 seconds the alertmanager container dies, starts again and fails again cyclically.

**Environment**

* System information:

`Linux 5.11.0-7612-generic x86_64`

* Alertmanager version:

`version=0.21.0, branch=master, revision=22ac6dff21901bfce14545da59b37a1aaca0db3a`

* Prometheus version:

`version=2.26.0, branch=HEAD, revision=3cafc58827d1ebd1a67749f88be4218f0bab3d8d`

* Alertmanager configuration file:
```
not relevant, see below
```

* Prometheus configuration file:
```
not relevant, see below
```

* docker run:

```
docker run -d -p 9093:9093 \
     --restart=unless-stopped \
     --hostname=alertmanager \
     --name alertmanager \
     -v /usr/local/etc/alertmanager:/etc/alertmanager \
     -v /etc/timezone:/etc/timezone:ro \
     -v /etc/localtime:/etc/localtime:ro \
     -e TZ=Europe/Berlin \
     prom/alertmanager:master \
     --config.file="/etc/alertmanager/alertmanager.yml" \
     --storage.path=/etc/alertmanager/data \
     --data.retention=168h \
     --web.external-url=https://alertmanager.domain.xy \
     --log.level=debug \
     --cluster.listen-address=
```

* Logs:
```
level=info ts=2021-04-17T16:10:34.766Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.21.0, branch=master, revision=22ac6dff21901bfce14545da59b37a1aaca0db3a)"
level=info ts=2021-04-17T16:10:34.766Z caller=main.go:222 build_context="(go=go1.16.3, user=root@c386f44bafa0, date=20210413-15:17:06)"
level=debug ts=2021-04-17T16:10:34.827Z caller=main.go:360 externalURL=https://alertmanager.domain.xy
level=info ts=2021-04-17T16:10:34.827Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
level=info ts=2021-04-17T16:10:34.828Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/alertmanager.yml
level=debug ts=2021-04-17T16:10:34.834Z caller=main.go:477 routePrefix=/
level=info ts=2021-04-17T16:10:34.835Z caller=main.go:497 msg=Listening address=:9093
level=info ts=2021-04-17T16:10:34.838Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=debug ts=2021-04-17T16:11:17.371Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert="Let's Encrypt ssl certificate will expire within 1 Month[36fbef0][resolved]"
level=debug ts=2021-04-17T16:11:17.371Z caller=dispatch.go:474 component=dispatcher aggrGroup="{}:{alertname=\"Let's Encrypt ssl certificate will expire within 1 Month\", server=\"arkanoid\"}" msg=flushing alerts="[Let's Encrypt ssl certificate will expire within 1 Month[36fbef0][resolved]]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xafe865]
goroutine 152 [running]:
github.com/prometheus/alertmanager/cluster.(*Peer).WaitReady(0x0, 0x113be38, 0xc00017c210, 0x125, 0x170)
        /app/cluster/cluster.go:591 +0x45
github.com/prometheus/alertmanager/notify.(*GossipSettleStage).Exec(0xc0008074e0, 0x113be38, 0xc00017c210, 0x11258a0, 0xc00036a090, 0xc0002884e0, 0x1, 0x1, 0x1111fb0, 0x1111fb0, ...)
        /app/notify/notify.go:433 +0xa3
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc00062afa0, 0x5, 0x5, 0x113be38, 0xc00017c210, 0x11258a0, 0xc00036a090, 0xc0002884e0, 0x1, 0x1, ...)
        /app/notify/notify.go:385 +0x102
github.com/prometheus/alertmanager/notify.RoutingStage.Exec(0xc00036a000, 0x113be38, 0xc00017c210, 0x11258a0, 0xc00036a090, 0xc0002884e0, 0x1, 0x1, 0x14, 0x0, ...)
        /app/notify/notify.go:371 +0x1e2
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1(0x113be38, 0xc00017c210, 0xc0002884e0, 0x1, 0x1, 0xc000124140)
        /app/dispatch/dispatch.go:300 +0xa6
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run.func1(0xc0002884e0, 0x1, 0x1, 0x4)
        /app/dispatch/dispatch.go:416 +0x55
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).flush(0xc00010b7a0, 0xc0002eff60)
        /app/dispatch/dispatch.go:476 +0x529
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run(0xc00010b7a0, 0xc00019ce00)
        /app/dispatch/dispatch.go:415 +0x5a5
created by github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert
        /app/dispatch/dispatch.go:299 +0x279

```

### Is the error reproduceable? if yes, how?
Definitely yes. Triggering the segmentation violation is reproduceable and related to the alertmanager flag `--cluster.listen-address=` or `--cluster.listen-address=""`. 

### Temporary solution
As workaround, I omited the `cluster.*` flag. It looks trivial, but it took a time to analyze and to came up to the conclusion. 

The tag `latest` on docker hasn't the bug and works as expected 🚀

**Comment by Teriand** [comment]
Same in latest 0.22.0-rc0 version:

```
level=info ts=2021-05-06T07:21:24.029Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.0-rc.0, branch=HEAD, revision=8ec96dbfeb3cbe5d160e20dd57520996cd2633e6)"
level=info ts=2021-05-06T07:21:24.029Z caller=main.go:222 build_context="(go=go1.16.3, user=root@4bf45e384ce7, date=20210504-19:46:48)"
level=info ts=2021-05-06T07:21:24.066Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/opt/prometheus/etc/alertmanager/am.yml
level=info ts=2021-05-06T07:21:24.068Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=/opt/prometheus/etc/alertmanager/am.yml
level=info ts=2021-05-06T07:21:24.076Z caller=main.go:497 msg=Listening address=:9093
level=info ts=2021-05-06T07:21:24.076Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xb06f45]
goroutine 154 [running]:
github.com/prometheus/alertmanager/cluster.(*Peer).WaitReady(0x0, 0x115c038, 0xc000978330, 0x3e, 0x40db1b)
/app/cluster/cluster.go:594 +0x45
github.com/prometheus/alertmanager/notify.(*GossipSettleStage).Exec(0xc000306910, 0x115c038, 0xc000978330, 0x1145920, 0xc000937f80, 0xc00000ed08, 0x1, 0x1, 0x1131ae8, 0x1131ae8, ...)
/app/notify/notify.go:433 +0xa3
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc0005f4eb0, 0x5, 0x5, 0x115c038, 0xc000978330, 0x1145920, 0xc000937f80, 0xc00000ed08, 0x1, 0x1, ...)
/app/notify/notify.go:385 +0x102
github.com/prometheus/alertmanager/notify.RoutingStage.Exec(0xc000937410, 0x115c038, 0xc000978330, 0x1145920, 0xc000937f80, 0xc00000ed08, 0x1, 0x1, 0xf, 0x19, ...)
/app/notify/notify.go:371 +0x1e2
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1(0x115c038, 0xc000978330, 0xc00000ed08, 0x1, 0x1, 0xc0000be000)
/app/dispatch/dispatch.go:301 +0xa6
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run.func1(0xc00000ed08, 0x1, 0x1, 0x4)
/app/dispatch/dispatch.go:417 +0x55
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).flush(0xc000614cf0, 0xc000965f60)
/app/dispatch/dispatch.go:477 +0x529
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run(0xc000614cf0, 0xc0003046e0)
/app/dispatch/dispatch.go:416 +0x5a5
created by github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert
/app/dispatch/dispatch.go:300 +0x279

```

**Comment by roidelapluie** [comment]
cc @gotjosh can you please look at this? Possibly introduced by #2487

**Comment by roidelapluie** [comment]
This should be fixed in 0.22.0-rc.1, can you please try? The final release will happen really soon but I would like some feedback on this of possible.

**Comment by Teriand** [comment]
Confirm, 0.22.0-rc1 work with --cluster.listen-address= 
thx!

**Comment by jobenvil** [comment]
No, it doesn't work. You can reproduce it when you click on the GUI on the Status tab. You got an `502` error

![image](https://user-images.githubusercontent.com/11994245/118115554-63ea8d80-b3e9-11eb-847c-e7205ddf5792.png)

It starts as it should be:

```
level=info ts=2021-05-13T10:49:23.402Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.0-rc.1, branch=HEAD, revision=a2bbecc356c2e9cbef82c5f49e71105e1a4ade5c)"
level=info ts=2021-05-13T10:49:23.402Z caller=main.go:222 build_context="(go=go1.16.4, user=root@a1b306c81fae, date=20210510-20:04:31)"
level=info ts=2021-05-13T10:49:23.439Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
level=info ts=2021-05-13T10:49:23.440Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/alertmanager.yml
level=info ts=2021-05-13T10:49:23.447Z caller=main.go:506 msg=Listening address=:9093
level=info ts=2021-05-13T10:49:23.448Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
```
but, after you click on "status" on WebGUI, following errors are thrown:

```
2021/05/13 12:49:56 http: panic serving 192.168.178.50:1122: runtime error: invalid memory address or nil pointer dereference
goroutine 178 [running]:
net/http.(*conn).serve.func1(0xc0004c6000)
        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0xe48620, 0x16d02e0)
        /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/prometheus/alertmanager/cluster.(*Peer).Ready(0x0, 0xc0001abba0)
        /app/cluster/cluster.go:582 +0x22
github.com/prometheus/alertmanager/cluster.(*Peer).Status(0x0, 0xc0001abba0, 0xc000581320)
        /app/cluster/cluster.go:601 +0x2b
github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler(0xc0000bd8c0, 0xc0008e2500, 0x0, 0x0)
        /app/api/v2/api.go:177 +0x31d
github.com/prometheus/alertmanager/api/v2/restapi/operations/general.GetStatusHandlerFunc.Handle(0xc00041ac00, 0xc0008e2500, 0xc0008e2400, 0x1145f20)
        /app/api/v2/restapi/operations/general/get_status.go:33 +0x30
github.com/prometheus/alertmanager/api/v2/restapi/operations/general.(*GetStatus).ServeHTTP(0xc0002fe570, 0x11594f0, 0xc0008fe0e0, 0xc0008e2500)
        /app/api/v2/restapi/operations/general/get_status.go:68 +0x16c
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x11594f0, 0xc0008fe0e0, 0xc0008e2500)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc00041b2e0, 0x11594f0, 0xc0008fe0e0, 0xc0008e2500)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x11594f0, 0xc0008fe0e0, 0xc0008e2300)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:78 +0x359
net/http.HandlerFunc.ServeHTTP(0xc000619c60, 0x11594f0, 0xc0008fe0e0, 0xc0008e2300)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x11594f0, 0xc0008fe0e0, 0xc0008e2300)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/spec.go:46 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xc000593640, 0x11594f0, 0xc0008fe0e0, 0xc0008e2300)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x11594f0, 0xc0008fe0e0, 0xc0008e2300)
        /go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc000619c80, 0x11594f0, 0xc0008fe0e0, 0xc0008e2300)
        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.StripPrefix.func1(0x11594f0, 0xc0008fe0e0, 0xc0008e2200)
        /usr/local/go/src/net/http/server.go:2112 +0x234
net/http.HandlerFunc.ServeHTTP(0xc0001f3590, 0x11594f0, 0xc0008fe0e0, 0xc0008e2200)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/alertmanager/api.(*API).limitHandler.func1(0x11594f0, 0xc0008fe0e0, 0xc0008e2200)
        /app/api/api.go:222 +0xc2
net/http.HandlerFunc.ServeHTTP(0xc0005b2e40, 0x11594f0, 0xc0008fe0e0, 0xc0008e2200)
        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0005c78c0, 0x11594f0, 0xc0008fe0e0, 0xc0008e2200)
        /usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0002fa0e0, 0x11594f0, 0xc0008fe0e0, 0xc0008e2200)
        /usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0004c6000, 0x115c0b8, 0xc0001e8080)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b

```

**Comment by Teriand** [comment]
yes, i dont test webui, only starting.
confirm webui error
