### ISSUE TITLE
Error in Alertmanager 0.22.0-rc.1: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bimmerkiev** [prometheus/alertmanager#2580]
**What did you do?**
1.Opened Alertmanager UI and go to "status" page.
2.Tried create the "New Silence":
If I fill in field "Matchers" the right exporession, for example namespace="kube-system" , and pushing the button "Preview alerts" it respond "Network error".  The same reply, if I pushing the button "create". 
**What did you expect to see?**
1.Status information page.
2.Preview or create the "silence"
**What did you see instead? Under which circumstances?**
Blank page with "Network error" string.
**Environment**
CentOS Linux release 7.8.2003 (Core)

* System information:

Linux 3.10.0-1127.19.1.el7.x86_64 x86_64
* Alertmanager version:
alertmanager, version 0.22.0-rc.1 (branch: HEAD, revision: a2bbecc356c2e9cbef82c5f49e71105e1a4ade5c)
  build user:       root@a1b306c81fae
  build date:       20210510-20:04:31
  go version:       go1.16.4
  platform:         linux/amd64

* Alertmanager configuration file:
```
global:
  resolve_timeout: 3m
templates:
- '/etc/alertmanager/templates/*.tmpl'
receivers:
- name: pagerduty
  pagerduty_configs:
  - client_url: http://x.x.x.x:9093/
    description: '{{ if .CommonAnnotations.summary }}{{ .CommonAnnotations.summary
      }}{{ end }}'
    routing_key: $key
    severity: '{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower
      }}{{ end }}'

route:
  group_by:
  - alertname
  - cluster
  - service
  - env
  group_interval: 5m
  group_wait: 30s
  receiver: pagerduty
  repeat_interval: 4h
  routes:
  - group_wait: 10s
    match:
      severity: critical
    receiver: pagerduty
```

* Logs:
```
May 14 12:26:33 stage alertmanager[13995]: level=info ts=2021-05-14T12:26:33.267Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.0-rc.1, branch=HEAD, revision=a2bbecc356c2e9cbef82c5f49e71105
May 14 12:26:33 stage alertmanager[13995]: level=info ts=2021-05-14T12:26:33.267Z caller=main.go:222 build_context="(go=go1.16.4, user=root@a1b306c81fae, date=20210510-20:04:31)"
May 14 12:26:33 stage alertmanager[13995]: level=info ts=2021-05-14T12:26:33.324Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
May 14 12:26:33 stage alertmanager[13995]: level=info ts=2021-05-14T12:26:33.324Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/alertmanager
May 14 12:26:33 stage alertmanager[13995]: level=info ts=2021-05-14T12:26:33.328Z caller=main.go:506 msg=Listening address=0.0.0.0:9093
May 14 12:26:33 stage alertmanager[13995]: level=info ts=2021-05-14T12:26:33.328Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
May 14 12:26:35 stage alertmanager[13995]: level=error ts=2021-05-14T12:26:35.094Z caller=dispatch.go:310 component=dispatcher msg="Notify for alerts failed" num_alerts=12 err="pagerduty/pagerduty[0]: notify retry
May 14 12:26:50 stage alertmanager[13995]: 2021/05/14 12:26:50 http: panic serving 188.42.195.116:62809: runtime error: invalid memory address or nil pointer dereference
May 14 12:26:50 stage alertmanager[13995]: goroutine 147 [running]:
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve.func1(0xc0008ba000)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1824 +0x153
May 14 12:26:50 stage alertmanager[13995]: panic(0xe48620, 0x16d02e0)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/runtime/panic.go:971 +0x499
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Ready(0x0, 0xc0003badc0)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:582 +0x22
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Status(0x0, 0xc0003badc0, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:601 +0x2b
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler(0xc0000aaf20, 0xc00063b200, 0x0, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/api.go:177 +0x31d
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.GetStatusHandlerFunc.Handle(0xc0005a35e0, 0xc00063b200, 0xc00063b100, 0x1145f20)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:33 +0x30
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.(*GetStatus).ServeHTTP(0xc0005307f8, 0x11594f0, 0xc00096c700, 0xc00063b200)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:68 +0x16c
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x11594f0, 0xc00096c700, 0xc00063b200)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/operation.go:28 +0x75
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0005a3cf0, 0x11594f0, 0xc00096c700, 0xc00063b200)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewRouter.func1(0x11594f0, 0xc00096c700, 0xc00063b000)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:78 +0x359
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262a0, 0x11594f0, 0xc00096c700, 0xc00063b000)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.Spec.func1(0x11594f0, 0xc00096c700, 0xc00063b000)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/spec.go:46 +0x1a3
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0003f1880, 0x11594f0, 0xc00096c700, 0xc00063b000)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/rs/cors.(*Cors).Handler.func1(0x11594f0, 0xc00096c700, 0xc00063b000)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262e0, 0x11594f0, 0xc00096c700, 0xc00063b000)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.StripPrefix.func1(0x11594f0, 0xc00096c700, 0xc000c75d00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2112 +0x234
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc00065fa40, 0x11594f0, 0xc00096c700, 0xc000c75d00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api.(*API).limitHandler.func1(0x11594f0, 0xc00096c700, 0xc000c75d00)
May 14 12:26:50 stage alertmanager[13995]: /app/api/api.go:222 +0xc2
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001c6680, 0x11594f0, 0xc00096c700, 0xc000c75d00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.(*ServeMux).ServeHTTP(0xc0006392c0, 0x11594f0, 0xc00096c700, 0xc000c75d00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2448 +0x1ad
May 14 12:26:50 stage alertmanager[13995]: net/http.serverHandler.ServeHTTP(0xc00066c000, 0x11594f0, 0xc00096c700, 0xc000c75d00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2887 +0xa3
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve(0xc0008ba000, 0x115c0b8, 0xc0005eb180)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1952 +0x8cd
May 14 12:26:50 stage alertmanager[13995]: created by net/http.(*Server).Serve
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:3013 +0x39b
May 14 12:26:50 stage alertmanager[13995]: 2021/05/14 12:26:50 http: panic serving 188.42.195.116:62811: runtime error: invalid memory address or nil pointer dereference
May 14 12:26:50 stage alertmanager[13995]: goroutine 150 [running]:
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve.func1(0xc0008ba140)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1824 +0x153
May 14 12:26:50 stage alertmanager[13995]: panic(0xe48620, 0x16d02e0)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/runtime/panic.go:971 +0x499
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Ready(0x0, 0xc0001a44b0)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:582 +0x22
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Status(0x0, 0xc0001a44b0, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:601 +0x2b
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler(0xc0000aaf20, 0xc000541d00, 0x0, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/api.go:177 +0x31d
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.GetStatusHandlerFunc.Handle(0xc0005a35e0, 0xc000541d00, 0xc000541c00, 0x1145f20)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:33 +0x30
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.(*GetStatus).ServeHTTP(0xc0005307f8, 0x11594f0, 0xc000912460, 0xc000541d00)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:68 +0x16c
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x11594f0, 0xc000912460, 0xc000541d00)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/operation.go:28 +0x75
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0005a3cf0, 0x11594f0, 0xc000912460, 0xc000541d00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewRouter.func1(0x11594f0, 0xc000912460, 0xc000541b00)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:78 +0x359
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262a0, 0x11594f0, 0xc000912460, 0xc000541b00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.Spec.func1(0x11594f0, 0xc000912460, 0xc000541b00)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/spec.go:46 +0x1a3
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0003f1880, 0x11594f0, 0xc000912460, 0xc000541b00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/rs/cors.(*Cors).Handler.func1(0x11594f0, 0xc000912460, 0xc000541b00)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262e0, 0x11594f0, 0xc000912460, 0xc000541b00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.StripPrefix.func1(0x11594f0, 0xc000912460, 0xc000c74500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2112 +0x234
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc00065fa40, 0x11594f0, 0xc000912460, 0xc000c74500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api.(*API).limitHandler.func1(0x11594f0, 0xc000912460, 0xc000c74500)
May 14 12:26:50 stage alertmanager[13995]: /app/api/api.go:222 +0xc2
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001c6680, 0x11594f0, 0xc000912460, 0xc000c74500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.(*ServeMux).ServeHTTP(0xc0006392c0, 0x11594f0, 0xc000912460, 0xc000c74500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2448 +0x1ad
May 14 12:26:50 stage alertmanager[13995]: net/http.serverHandler.ServeHTTP(0xc00066c000, 0x11594f0, 0xc000912460, 0xc000c74500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2887 +0xa3
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve(0xc0008ba140, 0x115c0b8, 0xc0005eb300)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1952 +0x8cd
May 14 12:26:50 stage alertmanager[13995]: created by net/http.(*Server).Serve
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:3013 +0x39b
May 14 12:26:50 stage alertmanager[13995]: 2021/05/14 12:26:50 http: panic serving 188.42.195.116:62810: runtime error: invalid memory address or nil pointer dereference
May 14 12:26:50 stage alertmanager[13995]: goroutine 149 [running]:
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve.func1(0xc0008ba0a0)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1824 +0x153
May 14 12:26:50 stage alertmanager[13995]: panic(0xe48620, 0x16d02e0)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/runtime/panic.go:971 +0x499
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Ready(0x0, 0xc0003bbbf0)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:582 +0x22
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Status(0x0, 0xc0003bbbf0, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:601 +0x2b
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler(0xc0000aaf20, 0xc00063b600, 0x0, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/api.go:177 +0x31d
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.GetStatusHandlerFunc.Handle(0xc0005a35e0, 0xc00063b600, 0xc00063b500, 0x1145f20)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:33 +0x30
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.(*GetStatus).ServeHTTP(0xc0005307f8, 0x11594f0, 0xc00096c8c0, 0xc00063b600)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:68 +0x16c
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x11594f0, 0xc00096c8c0, 0xc00063b600)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/operation.go:28 +0x75
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0005a3cf0, 0x11594f0, 0xc00096c8c0, 0xc00063b600)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewRouter.func1(0x11594f0, 0xc00096c8c0, 0xc00063b400)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:78 +0x359
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262a0, 0x11594f0, 0xc00096c8c0, 0xc00063b400)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.Spec.func1(0x11594f0, 0xc00096c8c0, 0xc00063b400)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/spec.go:46 +0x1a3
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0003f1880, 0x11594f0, 0xc00096c8c0, 0xc00063b400)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/rs/cors.(*Cors).Handler.func1(0x11594f0, 0xc00096c8c0, 0xc00063b400)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262e0, 0x11594f0, 0xc00096c8c0, 0xc00063b400)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.StripPrefix.func1(0x11594f0, 0xc00096c8c0, 0xc000257500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2112 +0x234
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc00065fa40, 0x11594f0, 0xc00096c8c0, 0xc000257500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api.(*API).limitHandler.func1(0x11594f0, 0xc00096c8c0, 0xc000257500)
May 14 12:26:50 stage alertmanager[13995]: /app/api/api.go:222 +0xc2
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001c6680, 0x11594f0, 0xc00096c8c0, 0xc000257500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.(*ServeMux).ServeHTTP(0xc0006392c0, 0x11594f0, 0xc00096c8c0, 0xc000257500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2448 +0x1ad
May 14 12:26:50 stage alertmanager[13995]: net/http.serverHandler.ServeHTTP(0xc00066c000, 0x11594f0, 0xc00096c8c0, 0xc000257500)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2887 +0xa3
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve(0xc0008ba0a0, 0x115c0b8, 0xc000657840)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1952 +0x8cd
May 14 12:26:50 stage alertmanager[13995]: created by net/http.(*Server).Serve
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:3013 +0x39b
May 14 12:26:50 stage alertmanager[13995]: 2021/05/14 12:26:50 http: panic serving 188.42.195.116:62829: runtime error: invalid memory address or nil pointer dereference
May 14 12:26:50 stage alertmanager[13995]: goroutine 162 [running]:
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve.func1(0xc000110960)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1824 +0x153
May 14 12:26:50 stage alertmanager[13995]: panic(0xe48620, 0x16d02e0)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/runtime/panic.go:971 +0x499
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Ready(0x0, 0xc0001a5710)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:582 +0x22
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/cluster.(*Peer).Status(0x0, 0xc0001a5710, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/cluster/cluster.go:601 +0x2b
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2.(*API).getStatusHandler(0xc0000aaf20, 0xc000706100, 0x0, 0x0)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/api.go:177 +0x31d
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.GetStatusHandlerFunc.Handle(0xc0005a35e0, 0xc000706100, 0xc000706000, 0x1145f20)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:33 +0x30
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api/v2/restapi/operations/general.(*GetStatus).ServeHTTP(0xc0005307f8, 0x11594f0, 0xc0009127e0, 0xc000706100)
May 14 12:26:50 stage alertmanager[13995]: /app/api/v2/restapi/operations/general/get_status.go:68 +0x16c
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x11594f0, 0xc0009127e0, 0xc000706100)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/operation.go:28 +0x75
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0005a3cf0, 0x11594f0, 0xc0009127e0, 0xc000706100)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.NewRouter.func1(0x11594f0, 0xc0009127e0, 0xc000541f00)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:78 +0x359
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262a0, 0x11594f0, 0xc0009127e0, 0xc000541f00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/go-openapi/runtime/middleware.Spec.func1(0x11594f0, 0xc0009127e0, 0xc000541f00)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/spec.go:46 +0x1a3
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0003f1880, 0x11594f0, 0xc0009127e0, 0xc000541f00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/rs/cors.(*Cors).Handler.func1(0x11594f0, 0xc0009127e0, 0xc000541f00)
May 14 12:26:50 stage alertmanager[13995]: /go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001262e0, 0x11594f0, 0xc0009127e0, 0xc000541f00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.StripPrefix.func1(0x11594f0, 0xc0009127e0, 0xc000541e00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2112 +0x234
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc00065fa40, 0x11594f0, 0xc0009127e0, 0xc000541e00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: github.com/prometheus/alertmanager/api.(*API).limitHandler.func1(0x11594f0, 0xc0009127e0, 0xc000541e00)
May 14 12:26:50 stage alertmanager[13995]: /app/api/api.go:222 +0xc2
May 14 12:26:50 stage alertmanager[13995]: net/http.HandlerFunc.ServeHTTP(0xc0001c6680, 0x11594f0, 0xc0009127e0, 0xc000541e00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2069 +0x44
May 14 12:26:50 stage alertmanager[13995]: net/http.(*ServeMux).ServeHTTP(0xc0006392c0, 0x11594f0, 0xc0009127e0, 0xc000541e00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2448 +0x1ad
May 14 12:26:50 stage alertmanager[13995]: net/http.serverHandler.ServeHTTP(0xc00066c000, 0x11594f0, 0xc0009127e0, 0xc000541e00)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:2887 +0xa3
May 14 12:26:50 stage alertmanager[13995]: net/http.(*conn).serve(0xc000110960, 0x115c0b8, 0xc0004a9a40)
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:1952 +0x8cd
May 14 12:26:50 stage alertmanager[13995]: created by net/http.(*Server).Serve
May 14 12:26:50 stage alertmanager[13995]: /usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by beorn7** [comment]
Related to https://github.com/prometheus/alertmanager/issues/2549 ? @roidelapluie @gotjosh
