### ISSUE TITLE
Installing alertmanager 0.22.2 in windows under a path with parenthesis fails

### ISSUE THREAD

**Issue by ruifigueira** [prometheus/alertmanager#2639]
**What did you do?**

We had an alertmanager 0.21.0 installation under `C:\Program Files (x86)\alertmanager` that was running without any issues and we upgraded it to 0.22.2

**What did you expect to see?**

We expected for it ro run normally

**What did you see instead? Under which circumstances?**

It fails with the following error:

```
C:\Program Files (x86)\alertmanager>alertmanager.exe --web.listen-address="0.0.0.0:9093" --storage.path="C:\ProgramData\alertmanager" --cluster.listen-address=
level=info ts=2021-06-29T08:22:44.522Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.2, branch=HEAD, revision=44f8adc06af5101ad64bd8b9c8b18273f2922051)"
level=info ts=2021-06-29T08:22:44.525Z caller=main.go:222 build_context="(go=go1.16.4, user=root@281aef8c2e93, date=20210602-07:53:08)"
panic: Invalid schema provided to SchemaValidator: open c:\program files (x86)\alertmanager\.root: The system cannot find the file specified.

goroutine 1 [running]:
github.com/go-openapi/validate.NewSchemaValidator(0xc000468900, 0x1728d00, 0xc000133100, 0xc0004639b0, 0x7, 0x19f2688, 0xc00009cf30, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/go-openapi/validate@v0.20.2/schema.go:72 +0xee5
github.com/go-openapi/runtime/middleware.newUntypedParamBinder(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/parameter.go:47 +0x1b6
github.com/go-openapi/runtime/middleware.NewUntypedRequestBinder(0xc00034b5c0, 0xc000133100, 0x19f2688, 0xc00009cf30, 0xc00034b620)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/request.go:40 +0x168
github.com/go-openapi/runtime/middleware.(*defaultRouteBuilder).AddRoute(0xc0007cf0f8, 0x17ec7fe, 0x4, 0xc0004e1c00, 0x9, 0xc00016ad20)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:442 +0x628
github.com/go-openapi/runtime/middleware.DefaultRouter(0xc0000a0000, 0x19f5b58, 0xc0000c54a0, 0x16fac40, 0xc000413b50)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:141 +0x168
github.com/go-openapi/runtime/middleware.NewRouter(0xc00034ab70, 0x19d65c0, 0xc000413b50, 0xc000413b50, 0xc00034ab70)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/router.go:73 +0xe5
github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler(0xc00034ab70, 0x0, 0xc00034ab70, 0xc00034ab70)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.28/middleware/context.go:621 +0x85
github.com/prometheus/alertmanager/api/v2.NewAPI.func1(0x0, 0x16f7ac0, 0xc00034a101)
        /app/api/v2/api.go:114 +0x69
github.com/prometheus/alertmanager/api/v2/restapi/operations.(*AlertmanagerAPI).Serve(0xc0000c54a0, 0x0, 0x0, 0x0)
        /app/api/v2/restapi/operations/alertmanager_api.go:367 +0x5c
github.com/prometheus/alertmanager/api/v2.NewAPI(0x19ea680, 0xc0003ec540, 0xc00038b7f0, 0xc0003fe780, 0xc0003d4f60, 0x0, 0x0, 0x19d3ec0, 0xc0003f2d50, 0x19e7410, ...)
        /app/api/v2/api.go:128 +0x6a5
github.com/prometheus/alertmanager/api.New(0x19ea680, 0xc0003ec540, 0xc0003d4f60, 0xc0003fe780, 0x0, 0x0, 0x0, 0x0, 0x19d3ec0, 0xc0003f2ab0, ...)
        /app/api/api.go:122 +0x3c5
main.run(0x0)
        /app/cmd/alertmanager/main.go:346 +0x35ba
main.main()
        /app/cmd/alertmanager/main.go:175 +0x29
```

If we change it to any path with parenthesis, for instance, `C:\alertmanager (0.22.2)` we have the same error:

```
C:\alertmanager (0.22.2)>alertmanager.exe --web.listen-address="0.0.0.0:9093" --storage.path="C:\ProgramData\alertmanager" --cluster.listen-address=
level=info ts=2021-06-29T08:25:36.933Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.2, branch=HEAD, revision=44f8adc06af5101ad64bd8b9c8b18273f2922051)"
level=info ts=2021-06-29T08:25:36.936Z caller=main.go:222 build_context="(go=go1.16.4, user=root@281aef8c2e93, date=20210602-07:53:08)"
level=info ts=2021-06-29T08:25:37.018Z caller=silence.go:398 component=silences msg="Creating shutdown snapshot failed" err="rename C:\\ProgramData\\alertmanager\\silences.419ef32796198506 C:\\ProgramData\\alertmanager\\silences: Access is denied."
panic: Invalid schema provided to SchemaValidator: open c:\alertmanager (0.22.2)\.root: The system cannot find the file specified.

goroutine 1 [running]:
github.com/go-openapi/validate.NewSchemaValidator(0xc00041c900, 0x1728d00, 0xc000135100, 0xc000432470, 0x7, 0x19f2688, 0xc00009cf30, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/go-openapi/validate@v0.20.2/schema.go:72 +0xee5
... (same stack as above)
```

If we don't have any parenthesis, for instance `C:\alertmanager 0.22.2` it runs with no issues:

```
C:\alertmanager 0.22.2>alertmanager.exe --web.listen-address="0.0.0.0:9093" --storage.path="C:\ProgramData\alertmanager" --cluster.listen-address=
level=info ts=2021-06-29T08:28:12.771Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.2, branch=HEAD, revision=44f8adc06af5101ad64bd8b9c8b18273f2922051)"
level=info ts=2021-06-29T08:28:12.771Z caller=main.go:222 build_context="(go=go1.16.4, user=root@281aef8c2e93, date=20210602-07:53:08)"
level=info ts=2021-06-29T08:28:12.824Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=alertmanager.yml
level=info ts=2021-06-29T08:28:12.839Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=alertmanager.yml
level=info ts=2021-06-29T08:28:12.851Z caller=main.go:514 msg=Listening address=0.0.0.0:9093
level=info ts=2021-06-29T08:28:12.861Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
```

**Environment**

* System information:

```
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
```

We also tested it in Windows 10, same issue.

* Alertmanager version:

```
alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build user:       root@281aef8c2e93
  build date:       20210602-07:53:08
  go version:       go1.16.4
  platform:         windows/amd64
```

* Prometheus version:

```
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@348b3e918312
  build date:       20210518-14:17:26
  go version:       go1.16.4
  platform:         windows/amd64
```

**Comment by pathcl** [comment]
I was able to reproduce the problem and somehow workaround it @ruifigueira 

- Grabbed the Schema: https://github.com/prometheus/alertmanager/blob/main/api/v2/openapi.yaml
- Convert to Json and placed it in 'C:\Program Files (x86)\alertmanager\.root'

```
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "Alertmanager API",
    "description": "API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/status": {
      "get": {
        "tags": [
          "general"
        ],
        "operationId": "getStatus",
        "description": "Get current status of an Alertmanager instance and its cluster",
        "responses": {
          "200": {
            "description": "Get status response",
            "schema": {
              "$ref": "#/definitions/alertmanagerStatus"
            }
          }
        }
      }
    },
    "/receivers": {
      "get": {
        "tags": [
          "receiver"
        ],
        "operationId": "getReceivers",
        "description": "Get list of all receivers (name of notification integrations)",
        "responses": {
          "200": {
            "description": "Get receivers response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/receiver"
              }
            }
          }
        }
      }
    },
    "/silences": {
      "get": {
        "tags": [
          "silence"
        ],
        "operationId": "getSilences",
        "description": "Get a list of silences",
        "responses": {
          "200": {
            "description": "Get silences response",
            "schema": {
              "$ref": "#/definitions/gettableSilences"
            }
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        },
        "parameters": [
          {
            "name": "filter",
            "in": "query",
            "description": "A list of matchers to filter silences by",
            "required": false,
            "type": "array",
            "collectionFormat": "multi",
            "items": {
              "type": "string"
            }
          }
        ]
      },
      "post": {
        "tags": [
          "silence"
        ],
        "operationId": "postSilences",
        "description": "Post a new silence or update an existing one",
        "parameters": [
          {
            "in": "body",
            "name": "silence",
            "description": "The silence to create",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postableSilence"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create / update silence response",
            "schema": {
              "type": "object",
              "properties": {
                "silenceID": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "404": {
            "description": "A silence with the specified ID was not found",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/silence/{silenceID}": {
      "parameters": [
        {
          "in": "path",
          "name": "silenceID",
          "type": "string",
          "format": "uuid",
          "required": true,
          "description": "ID of the silence to get"
        }
      ],
      "get": {
        "tags": [
          "silence"
        ],
        "operationId": "getSilence",
        "description": "Get a silence by its ID",
        "responses": {
          "200": {
            "description": "Get silence response",
            "schema": {
              "$ref": "#/definitions/gettableSilence"
            }
          },
          "404": {
            "description": "A silence with the specified ID was not found"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "delete": {
        "tags": [
          "silence"
        ],
        "operationId": "deleteSilence",
        "description": "Delete a silence by its ID",
        "parameters": [
          {
            "in": "path",
            "name": "silenceID",
            "type": "string",
            "format": "uuid",
            "required": true,
            "description": "ID of the silence to get"
          }
        ],
        "responses": {
          "200": {
            "description": "Delete silence response"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/alerts": {
      "get": {
        "tags": [
          "alert"
        ],
        "operationId": "getAlerts",
        "description": "Get a list of alerts",
        "parameters": [
          {
            "in": "query",
            "name": "active",
            "type": "boolean",
            "description": "Show active alerts",
            "default": true
          },
          {
            "in": "query",
            "name": "silenced",
            "type": "boolean",
            "description": "Show silenced alerts",
            "default": true
          },
          {
            "in": "query",
            "name": "inhibited",
            "type": "boolean",
            "description": "Show inhibited alerts",
            "default": true
          },
          {
            "in": "query",
            "name": "unprocessed",
            "type": "boolean",
            "description": "Show unprocessed alerts",
            "default": true
          },
          {
            "name": "filter",
            "in": "query",
            "description": "A list of matchers to filter alerts by",
            "required": false,
            "type": "array",
            "collectionFormat": "multi",
            "items": {
              "type": "string"
            }
          },
          {
            "name": "receiver",
            "in": "query",
            "description": "A regex matching receivers to filter alerts by",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Get alerts response",
            "schema": {
              "$ref": "#/definitions/gettableAlerts"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "post": {
        "tags": [
          "alert"
        ],
        "operationId": "postAlerts",
        "description": "Create new Alerts",
        "parameters": [
          {
            "in": "body",
            "name": "alerts",
            "description": "The alerts to create",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postableAlerts"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create alerts response"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/alerts/groups": {
      "get": {
        "tags": [
          "alertgroup"
        ],
        "operationId": "getAlertGroups",
        "description": "Get a list of alert groups",
        "parameters": [
          {
            "in": "query",
            "name": "active",
            "type": "boolean",
            "description": "Show active alerts",
            "default": true
          },
          {
            "in": "query",
            "name": "silenced",
            "type": "boolean",
            "description": "Show silenced alerts",
            "default": true
          },
          {
            "in": "query",
            "name": "inhibited",
            "type": "boolean",
            "description": "Show inhibited alerts",
            "default": true
          },
          {
            "name": "filter",
            "in": "query",
            "description": "A list of matchers to filter alerts by",
            "required": false,
            "type": "array",
            "collectionFormat": "multi",
            "items": {
              "type": "string"
            }
          },
          {
            "name": "receiver",
            "in": "query",
            "description": "A regex matching receivers to filter alerts by",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Get alert groups response",
            "schema": {
              "$ref": "#/definitions/alertGroups"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    }
  },
  "responses": {
    "BadRequest": {
      "description": "Bad request",
      "schema": {
        "type": "string"
      }
    },
    "InternalServerError": {
      "description": "Internal server error",
      "schema": {
        "type": "string"
      }
    }
  },
  "definitions": {
    "alertmanagerStatus": {
      "type": "object",
      "properties": {
        "cluster": {
          "$ref": "#/definitions/clusterStatus"
        },
        "versionInfo": {
          "$ref": "#/definitions/versionInfo"
        },
        "config": {
          "$ref": "#/definitions/alertmanagerConfig"
        },
        "uptime": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "cluster",
        "versionInfo",
        "config",
        "uptime"
      ]
    },
    "clusterStatus": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "ready",
            "settling",
            "disabled"
          ]
        },
        "peers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/peerStatus"
          }
        }
      },
      "required": [
        "status"
      ]
    },
    "alertmanagerConfig": {
      "type": "object",
      "properties": {
        "original": {
          "type": "string"
        }
      },
      "required": [
        "original"
      ]
    },
    "versionInfo": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "revision": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        },
        "buildUser": {
          "type": "string"
        },
        "buildDate": {
          "type": "string"
        },
        "goVersion": {
          "type": "string"
        }
      },
      "required": [
        "version",
        "revision",
        "branch",
        "buildUser",
        "buildDate",
        "goVersion"
      ]
    },
    "peerStatus": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "address": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "address"
      ]
    },
    "silence": {
      "type": "object",
      "properties": {
        "matchers": {
          "$ref": "#/definitions/matchers"
        },
        "startsAt": {
          "type": "string",
          "format": "date-time"
        },
        "endsAt": {
          "type": "string",
          "format": "date-time"
        },
        "createdBy": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      },
      "required": [
        "matchers",
        "startsAt",
        "endsAt",
        "createdBy",
        "comment"
      ]
    },
    "gettableSilence": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "status": {
              "$ref": "#/definitions/silenceStatus"
            },
            "updatedAt": {
              "type": "string",
              "format": "date-time"
            }
          },
          "required": [
            "id",
            "status",
            "updatedAt"
          ]
        },
        {
          "$ref": "#/definitions/silence"
        }
      ]
    },
    "postableSilence": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            }
          }
        },
        {
          "$ref": "#/definitions/silence"
        }
      ]
    },
    "silenceStatus": {
      "type": "object",
      "properties": {
        "state": {
          "type": "string",
          "enum": [
            "expired",
            "active",
            "pending"
          ]
        }
      },
      "required": [
        "state"
      ]
    },
    "gettableSilences": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/gettableSilence"
      }
    },
    "matchers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/matcher"
      },
      "minItems": 1
    },
    "matcher": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "isRegex": {
          "type": "boolean"
        },
        "isEqual": {
          "type": "boolean",
          "default": true
        }
      },
      "required": [
        "name",
        "value",
        "isRegex"
      ]
    },
    "alert": {
      "type": "object",
      "properties": {
        "labels": {
          "$ref": "#/definitions/labelSet"
        },
        "generatorURL": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "labels"
      ]
    },
    "gettableAlerts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/gettableAlert"
      }
    },
    "gettableAlert": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "annotations": {
              "$ref": "#/definitions/labelSet"
            },
            "receivers": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/receiver"
              }
            },
            "fingerprint": {
              "type": "string"
            },
            "startsAt": {
              "type": "string",
              "format": "date-time"
            },
            "updatedAt": {
              "type": "string",
              "format": "date-time"
            },
            "endsAt": {
              "type": "string",
              "format": "date-time"
            },
            "status": {
              "$ref": "#/definitions/alertStatus"
            }
          },
          "required": [
            "receivers",
            "fingerprint",
            "startsAt",
            "updatedAt",
            "endsAt",
            "annotations",
            "status"
          ]
        },
        {
          "$ref": "#/definitions/alert"
        }
      ]
    },
    "postableAlerts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/postableAlert"
      }
    },
    "postableAlert": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "startsAt": {
              "type": "string",
              "format": "date-time"
            },
            "endsAt": {
              "type": "string",
              "format": "date-time"
            },
            "annotations": {
              "$ref": "#/definitions/labelSet"
            }
          }
        },
        {
          "$ref": "#/definitions/alert"
        }
      ]
    },
    "alertGroups": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/alertGroup"
      }
    },
    "alertGroup": {
      "type": "object",
      "properties": {
        "labels": {
          "$ref": "#/definitions/labelSet"
        },
        "receiver": {
          "$ref": "#/definitions/receiver"
        },
        "alerts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/gettableAlert"
          }
        }
      },
      "required": [
        "labels",
        "receiver",
        "alerts"
      ]
    },
    "alertStatus": {
      "type": "object",
      "properties": {
        "state": {
          "type": "string",
          "enum": [
            "unprocessed",
            "active",
            "suppressed"
          ]
        },
        "silencedBy": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "inhibitedBy": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "state",
        "silencedBy",
        "inhibitedBy"
      ]
    },
    "receiver": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "labelSet": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "tags": [
    {
      "name": "general",
      "description": "General Alertmanager operations"
    },
    {
      "name": "receiver",
      "description": "Everything related to Alertmanager receivers"
    },
    {
      "name": "silence",
      "description": "Everything related to Alertmanager silences"
    },
    {
      "name": "alert",
      "description": "Everything related to Alertmanager alerts"
    }
  ]
}```


```

**Comment by TheMeier** [comment]
There has been no activity on this issue for a long time. In the meantime a lot of code has changed in Alertmanager. Therefore I assume that the original request is either not relevant anymore or has been addressed in some other way.

If I am wrong please re-open this issue or open a new one.
